### ISSUE TITLE
Create a Flashcard class

### ISSUE THREAD

**Issue by vhart** [vhart/InterviewFlashCards#1]
-Questions
-Answer
-Url? ->Image?

**Comment by mesbekmek** [comment]
@vhart is it going to be an array of questions and answers or is a flash card one nsstring question and one nsstring answer?

**Comment by mesbekmek** [comment]
I'm assuming it's going to be one nsstring question and one nsstring answer and an optional image url. Let me know what you're thinking.

**Comment by vhart** [comment]
I agree with your idea. Makes sense to have the array be of flash card objects. I'd suggest a property for question url and answer url in case our answers have images too

**Comment by vhart** [comment]
complete
