### ISSUE TITLE
Documentation at the top of each class

### ISSUE THREAD

**Issue by mesbekmek** [vhart/InterviewFlashCards#26]
Should we remove the automatic comments that are generated at the top e.g (Created by person X...) and replace with it a one-liner like "Interview Flash Cards", or should we remove it completely?

At Spotify, and I'm sure at Shopkeep as well, we don't really keep those auto-generated comments, but this isn't a company so I'm wondering what your thoughts are. @vhart @charleshkang

**Comment by charleshkang** [comment]
So I asked a few other devs and they said to remove them completely. They also said `Interview Flash Cards` would add nothing to the project, which I agree with...If we're going to remove the author line, just remove everything.

Lemme know what you guys think

**Comment by vhart** [comment]
They should be removed completely @mesbekmek @charleshkang. They add nothing really. If you guys agree then lets open an issue for it.

**Comment by charleshkang** [comment]
Yeah, sounds good to me
