### ISSUE TITLE
Crash after project run

### ISSUE THREAD

**Issue by RegularEric** [vhart/InterviewFlashCards#54]
Fork > clone > pod install > run > crash
<img width="1280" alt="screen shot 2017-02-26 at 12 50 17 am" src="https://cloud.githubusercontent.com/assets/17412583/23337492/a46472e2-fbbd-11e6-80fa-b5e552d228a2.png">

**Comment by vhart** [comment]
@promulgate thanks for raising this issue. Which branch is this crash on?

**Comment by RegularEric** [comment]
Should be master, I didn't do anything with branches. Just the above steps and ran it 3 times to check if it was a first time run bug

**Comment by vhart** [comment]
@Promulgate if you fetch the latest `master` it should be running. Just updating the project to reflect the refactor work I was doing.

**Comment by RegularEric** [comment]
It says already up to date if I do: git fetch origin master
Current crash is upon tapping an option - iOS technical or Data Structure

**Comment by vhart** [comment]
Hey @promulgate, you should be doing git pull upstream master

**Comment by vhart** [comment]
Then to update your remote repo you'd git push

**Comment by vhart** [comment]
Of course I'm assuming you forked

**Comment by RegularEric** [comment]
Weird I did fork but didn't have the remote. Anyway, works now. Hopefully I'll be able to contribute to fixing some of the swift issues hehe
